[2022-07-04 15:57:03,971: INFO: stage_01_prepare_data]: 
********************
[2022-07-04 15:57:03,971: INFO: stage_01_prepare_data]: >>>>> stage Prepare_Data started <<<<<
[2022-07-04 15:57:03,971: ERROR: stage_01_prepare_data]: [Errno 2] No such file or directory: 'configs/config.yaml'
Traceback (most recent call last):
  File "src/stage_01_prepare_data.py", line 51, in <module>
    main(config_path=parsed_args.config, params_path=parsed_args.params)
  File "src/stage_01_prepare_data.py", line 22, in main
    config = read_yaml(config_path)
  File "d:\myeuron\fulstackdatascientist\dvc-nlp-doc-project\dvc-nlp-project-with-docs\src\utils\common.py", line 9, in read_yaml
    with open(path_to_yaml) as yaml_file:
FileNotFoundError: [Errno 2] No such file or directory: 'configs/config.yaml'
[2022-07-04 15:57:44,130: INFO: stage_01_prepare_data]: 
********************
[2022-07-04 15:57:44,130: INFO: stage_01_prepare_data]: >>>>> stage Prepare_Data started <<<<<
[2022-07-04 15:57:44,133: INFO: common]: yaml file: configs/config.yaml loaded successfully
[2022-07-04 15:57:44,134: INFO: common]: yaml file: params.yaml loaded successfully
[2022-07-04 15:57:44,134: ERROR: stage_01_prepare_data]: 'artificats'
Traceback (most recent call last):
  File "src/stage_01_prepare_data.py", line 51, in <module>
    main(config_path=parsed_args.config, params_path=parsed_args.params)
  File "src/stage_01_prepare_data.py", line 34, in main
    artificats = config["artificats"]
KeyError: 'artificats'
